 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Norhan Khairy
 ******************************************************************************/
#include "Port.h"

/* Module Version 1.0.0 */
#define PORT_PBCFG_SW_MAJOR_VERSION			(1U)
#define PORT_PBCFG_SW_MINOR_VERSION			(0U)
#define	PORT_PBCFG_SW_PATCH_VERSION			(1U)

/* AUTOSAR Version 4.0.3 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION	(4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION	(0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION	(3U)


/* AUTOSAR Version checking between Port_PBcfg.c and Port Module files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of Port_PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.h and Port Modules files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of Port_PBcfg.h does not match the expected version"
#endif

/* Post Build array of structures for the configured pins
 *  one structure has: 
 * 			port_num, pin_num, direction, resistor, initial_value, pin_mode, pin_direction_changeable, pin_mode_changeable
 */
const Port_ConfigType Port_ConfigurationArray =
{
	/* PA0 */
	PORT_A, PA0, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PA1 */
	PORT_A, PA1, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PA2 */
	PORT_A, PA2, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PA3 */
	PORT_A, PA3, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PA4 */
	PORT_A, PA4, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PA5 */
	PORT_A, PA5, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PA6 */
	PORT_A, PA6, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PA7 */
	PORT_A, PA7, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB0 */
	PORT_B, PB0, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB1 */
	PORT_B, PB1, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB2 */
	PORT_B, PB2, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB3 */
	PORT_B, PB3, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB4 */
	PORT_B, PB4, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB5 */
	PORT_B, PB5, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB6 */
	PORT_B, PB6, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PB7 */
	PORT_B, PB7, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC0 */
	PORT_C, PC0, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC1 */
	PORT_C, PC1, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC2 */
	PORT_C, PC2, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC3 */
	PORT_C, PC3, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC4 */
	PORT_C, PC4, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC5 */
	PORT_C, PC5, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC6 */
	PORT_C, PC6, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PC7 */
	PORT_C, PC7, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD0 */
	PORT_D, PD0, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD1 */
	PORT_D, PD1, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD2 */
	PORT_D, PD2, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD3 */
	PORT_D, PD3, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD4 */
	PORT_D, PD4, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD5 */
	PORT_D, PD5, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD6 */
	PORT_D, PD6, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PD7 */
	PORT_D, PD7, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PE0 */
	PORT_E, PE0, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PE1 */
	PORT_E, PE1, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PE2 */
	PORT_E, PE2, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PE3 */
	PORT_E, PE3, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PE4 */
	PORT_E, PE4, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PE5 */
	PORT_E, PE5, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PF0 */
	PORT_F, PF0, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PF1 */
	PORT_F, PF1, OUTPUT, OFF, STD_LOW, DIO_MODE, STD_OFF, STD_OFF,
	/* PF2 */
	PORT_F, PF2, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PF3 */
	PORT_F, PF3, PORT_DEFAULT_PIN_DIRECTION, PORT_DEFAULT_PIN_RESISTANCE, PORT_DEFAULT_PIN_INITIAL_VALUE, PORT_DEFAULT_PIN_MODE, STD_OFF, STD_OFF,
	/* PF4 */
	PORT_F, PF4, INPUT, PULL_UP, STD_HIGH, DIO_MODE, STD_OFF, STD_OFF

};